version: "3"
services:
  mongodb:
    hostname: mongodb
    image : mongo
    container_name: mongodb
    environment:
     - PUID=1000
     - PGID=1000
    volumes:
     - ./mongodb/database:/data/db
    ports:
    - 27017:27017
    restart: always
  python:
    hostname: python
    build:
      context: ./python
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - mongodb
  python2:
    hostname: python2
    build:
      context: ./python
      dockerfile: ./Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
     - "8080:80"
    depends_on:
      - python
      - python2
