version: "3"
services:
  es-test:
    hostname: es-test
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: es-test
    environment:   
      - "ES_JAVA_OPTS=-Xms1012m -Xmx1012m"
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    networks:
      - test_network

  python:
    hostname: python
    container_name: python
    build:
      context: ./python
      dockerfile: ./Dockerfile
    ports:
      - "6000:5000"
    volumes:
      - .:/code
    depends_on:
      - es-test
    networks:
      - test_network

  python2:
    hostname: python2
    container_name: python2
    build:
      context: ./python
      dockerfile: ./Dockerfile
    ports:
      - "6001:5000"
    depends_on:
      - es-test
    networks:
      - test_network

  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
     - "8180:80"
    depends_on:
      - python
      - python2
    networks:
      - test_network


networks:
  test_network:


