version: "3"
services:
  mongodb:
    hostname: mongodb
    image : mongo
    container_name: mongodb
    environment:
     - PUID=1000
     - PGID=1000
    ports:
    - 27017:27017
    restart: always
    networks:
      - test_network

  python:
    hostname: python
    build:
      context: ./python
      dockerfile: ./Dockerfile
    ports:
      - "6000:5000"
    volumes:
      - .:/code
    depends_on:
      - mongodb
    networks:
      - test_network

  python2:
    hostname: python2
    build:
      context: ./python
      dockerfile: ./Dockerfile
    ports:
      - "6001:5000"
    depends_on:
      - mongodb
    networks:
      - test_network

  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
     - "8180:80"
    depends_on:
      - python
      - python2
    networks:
      - test_network


networks:
  test_network:


